name: CI-CD - Beta

on:
  push:
    tags:
      - 'v*-beta'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          cache: true
      
      - name: Format files
        run: |
          dart format --set-exit-if-changed .

      - name: Analyze files
        run: |
          flutter analyze .