name: CI-CD - Beta

on:
  push:
    tags:
      - 'v*-beta'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          cache: true
      
      - name: Format files
        run: |
          dart format --set-exit-if-changed .

      - name: Analyze files
        run: |
          flutter analyze .

  build_android:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          cache: true

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Build AAB
        run: |
          flutter build appbundle -t "lib/main.dart" --release
      
      - name: Build IOs
      - run: |
            cd ios 
            rm -rf Podfile.lock
            pod repo update
      - run: flutter build ios -t lib/main_dev.dart --release --no-codesign
      
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  
  release:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/

      - name: Generate Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/app/outputs/bundle/release/*"
          token: ${{ secrets.TOKEN }}
