name: CI - Android QA

on:
  push:
    branches:
      - task-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.3"
          channel: "stable"

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Update KeyStore password in gradle properties
        run: |
          sed -i 's/#{SIGNING_STORE_PASSWORD}#/${{ secrets.SIGNING_STORE_PASSWORD }}/g' android/key.properties

      - name: Update KeyStore key password in gradle properties
        run: |
          sed -i 's/#{SIGNING_KEY_PASSWORD}#/${{ secrets.SIGNING_KEY_PASSWORD }}/g' android/key.properties

      - name: Build APK
        run: |
          flutter build apk -t "lib/main.dart" --release

      - name: Get Version
        id: get_version
        run: echo version="$(grep -m1 '^version:' pubspec.yaml | awk '{print $2}' | sed 's/[[:space:]]//g')" >> $GITHUB_OUTPUT

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v${{ steps.get_version.outputs.version }}-beta
          token: ${{ secrets.TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/apk/release/
