name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          cache: true

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk -t "lib/main.dart" --release
