name: Remove Tags and Release

on:
  workflow_dispatch:

jobs:
  remove-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: List tags
        id: list_tags
        uses: jimschubert/query-tag-action@v1
        with:
          include: "v*-beta"

      - name: Print tags
        run: echo ${{ steps.list_tags.outputs.tag }}

      # - name: Eliminar etiquetas
      #   run: |
      #     TAGS="${{ steps.list_tags.outputs.tags }}"
      #     for tag in $TAGS; do
      #       if [[ $tag == *-beta* || $tag == *-release* ]]; then
      #         git push --delete origin $tag
      #       fi
      #     done
