name: Remove Tags and Release

on:
  workflow_dispatch:

jobs:
  remove-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Eliminar Etiquetas de -beta y -release
        run: |
          git fetch --tags
          for tag in $(git tag -l | grep -E '(-beta|-release)'); do
            git tag -d $tag
          done
          git fetch --prune --tags
          git push origin --delete $(git tag -l | grep -E '(-beta|-release)') # Elimina las etiquetas en el repositorio remoto
